### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by gohsianghwee** [yojimbo87/ArangoDB-NET#10]
Hi Yojimbo87,

I have some performance issues on the driver.

I have tested the code below with my arangosh

```
count=1;
startTime=+new Date();
console.log(startTime);
while(count <= 10000)
{
   db.someCollection.save({"Id":"1234567890123456789012345678901234", "Key":1234567, "Revision":1234567, "Name":"Mohamad Abu Bakar", "IC Number":"1234567-12-3444", "Department":"IT Department", "Height":1234, "DateOfBirth":"2015-01-27 03:33", "Salary":3333});
	count++;
}
endTime=+new Date();
console.log(endTime);
console.log("Total time taken:" + (endTime - startTime)/1000);
```

It took 3.375 seconds to complete the operation.

I do the similar thing with the .Net driver and it took almost 9.5797819. Almost triple of the arangosh. Here's the code in .Net

```csharp
public static void TestArangoDb()
{
    //ASettings.AddConnection("_system", "127.0.0.1", 8529, false, "_system");
    //var db = new ADatabase("_system");
    //db.Create("trial_sample");
    
    ASettings.AddConnection("trial_sample", "127.0.0.1", 8529, false, "trial_sample");
    var db2 = new ADatabase("trial_sample");
    
    db2.Collection.Create("someCollection");

    DateTime startTime = DateTime.Now;
    Console.WriteLine("Start Time: " + startTime.ToLongTimeString());

    for(int count=1; count <= 10000; count++)
    {
        var employee = new Employee();
        employee.Id = "1234567890123456789012345678901234";
        employee.Key = "1234567";
        employee.Revision = "1234567";
        employee.Name = "Mohamad Abu Bakar";
        employee.IcNumber = "1234567-12-3444";
        employee.Department = "IT Department";
        employee.Height = 1234;
        employee.DateOfBirth = new DateTime(2015, 1, 27, 3, 33, 3);
        employee.Salary = 3333;
        var result = db2.Document.Create<Employee>("someCollection", employee);
        
        //var updateDocument = new Dictionary<string, object>()
        //    .String("DocumentId", "SomeId");
        //db2.Document.Update(result.Value.String("_id"), updateDocument);
    }

    DateTime endTime = DateTime.Now;
    TimeSpan duration = endTime - startTime;
    Console.WriteLine("End Time: " + endTime.ToLongTimeString());
    Console.WriteLine("Total time taken: " + duration.TotalSeconds);
}

public class Employee 
{
    public string Id { get; set; }
    public string Key { get; set; }
    public string Revision { get; set; }
    public string Name { get; set; }
    public string IcNumber { get; set; }
    public string Email { get; set; }
    public string Department { get; set; }
    public double Height { get; set; }
    public DateTime DateOfBirth { get; set; }
    public decimal Salary { get; set; }
}
```

If I remove the comment for 

```csharp
var updateDocument = new Dictionary<string, object>()
    .String("DocumentId", "SomeId");

db2.Document.Update(result.Value.String("_id"), updateDocument);
```

The performance is almost 30 times. It took 99.8789133 seconds to complete. In fact, I just perform additional update to add additional column. 

Could you suggest on the problem on the code above? Thanks.

Cordially,
Goh

**Comment by gohsianghwee** [comment]
Very funny, the same set of .Net source code. I re-run again just now. It took me about 18.1162961 seconds as compared to the earlier 10 seconds. It almost double without any code changes. The only difference is that I do a lot of trial and error to boost the performance on another code-base for ArangoDB. The RAM remain 4.9/7.9 GB. Is there any configuration needed to be done?

**Comment by yojimbo87** [comment]
I haven't done any optimizations yet regarding the performance so I might only give you a quick explanation.

What you are doing is that you sequentially execute 10k insertions in a single thread environment. In other words next insert operation is performed after you receive the result from the previous one which makes the performance test estimation rather simple. For example if single insert operation takes 10ms to execute, including processing and network latency, then 10k inserts would take 10000 * 10ms = 100 seconds. Even if the operation takes 1ms (which would be pretty fast) it would still be 10000 * 1ms = 10 seconds to run 10k sequential inserts.

I highly doubt that you or anyone else is strictly limited to single threaded environment (especially in production) and that's why you should try to run your performance tests with some level of parallelism, e.g. 10 separate threads where each simultaneously inserts 1k documents. There are also some advice and general rules to benchmarking [here](http://stackoverflow.com/questions/4336009/how-to-get-a-fast-net-http-request?answertab=active#tab-top).

Why is there a big difference between driver and arangosh? As of this moment I don't know since I can't tell how arangosh works and how it is optimised. Anyway I will try to look into performance optimisations in the future and do some tests myself. It would also be interesting to see the benchmarks of drivers written in other languages for comparison.

**Comment by gohsianghwee** [comment]
Hi Yojimbo87,

Thanks again for taking time to look into my issue. I really appreciate your effort to help in this case. Hope to see if you can optimize the .Net framework in the future.

**Comment by mudbath** [comment]
Is this to do with proxy resolution?

**Comment by mudbath** [comment]
In your Connection.cs set the Proxy property to null for all HttpRequest calls. Read more here: https://msdn.microsoft.com/en-us/library/czdt10d3(v=vs.110).aspx

**Comment by yojimbo87** [comment]
I already tried this optimization earlier, but it did not have any noticable effect on performance in my tests though it's probably worth to expose it through API.

**Comment by otomazeli** [comment]
Hi, I'm look at ArangoDB and Neo4J to start a big project and I really liked ArangoDB over Neo4J but I'm concerning about the performance right now and as well the missing graph model implementation.
would it be available son?

**Comment by yojimbo87** [comment]
Hi, do you have some specific example or test to support/reproduce your concern about performance (so that it can be looked into and potentially optimized)? Regarding graph API - it's not yet implemented into the driver, but since it was already requested by several people it will be the next thing to be implemented for the next release.

**Comment by yojimbo87** [comment]
Merge request #32 improves performance when creating, updating and replacing documents/edges from generic objects by ~57%. 

On local machine single document creation with given `Employee` example object now takes on average ~0.4ms in 10k iteration loop using the driver. Raw .NET HTTP request (without any ArangoDB driver abstraction) takes ~0.35ms in 10k loop. Difference is made by conversion from generic object into `Dictionary<string, object>` which needs to be done because of attributes processing (such as IgnoreField, IgnoreNullValue and AliasField).
