### ISSUE TITLE
ExecuteNonQuery for Aql operations

### ISSUE THREAD

**Issue by jeff-pang** [yojimbo87/ArangoDB-NET#40]
Is there an equivalent of ExecuteNonQuery for Aql operations? Something that only returns the result of success/failure and maybe the id if it is an Insert or Upsert.

In the Upsert case, will need to know insert or upsert was performed ..

**Comment by yojimbo87** [comment]
Hi, there is no dedicated method for executing AQL queries that do not return any data since even after insert or upsert operation user can still retrieve data through return statement. However for the convenience I can add a method which won't have a result payload, but only success and status code information filled in. Is that ok?

**Comment by yojimbo87** [comment]
ExecuteNonQuery operation implemented and merged into the master and will be part of the 0.10.2 version on nuget.
