### ISSUE TITLE
Does not support user defined key

### ISSUE THREAD

**Issue by jeff-pang** [yojimbo87/ArangoDB-NET#6]
How do I specify user define key? It looked like its been limited with

document.Except("_id", "_key", "_rev")

**Comment by jeff-pang** [comment]
Thanks.

**Comment by jeff-pang** [comment]
Another quick qns. What is the difference between this branch and the triAGENS branch?

**Comment by yojimbo87** [comment]
triAGENS clone was created to add support for ArangoDB 2.x.x and some hotfixes. Since then I started reimplementing the driver in [reimplement](https://github.com/yojimbo87/ArangoDB-NET/tree/reimplement) branch to support more operations and provide better API with extensive docs. This branch will be merged with master soon since only very few things are left to be finished. If you want you can already use it, feedback and suggestions are very welcome.

**Comment by yojimbo87** [comment]
Supported in [reimplment](https://github.com/yojimbo87/ArangoDB-NET/tree/reimplement) branch. Docs available [here](https://github.com/yojimbo87/ArangoDB-NET/blob/reimplement/docs/DocumentOperations.md#create-document-with-user-defined-key).
